version: 0.0
os: linux
files:
  - source: redman.jar
    destination: /opt/redman/
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 300
      runas: root
