####################################################################################################
# spring
####################################################################################################
spring:
  thymeleaf:
    mode: HTML
#  output:
#    ansi:
#      enabled: ALWAYS
  security.oauth2.client.registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
