####################################################################################################
# spring
####################################################################################################
server:
  port: 80
spring:
  profiles:
    active: debug
  thymeleaf:
    mode: HTML
#  output:
#    ansi:
#      enabled: ALWAYS
  security.oauth2.client.registration:
          google:
            client-id: xxxxx
            client-secret: xxxxx
