####################################################################################################
# spring
####################################################################################################
spring:
  thymeleaf:
    mode: HTML
#  output:
#    ansi:
#      enabled: ALWAYS
