####################################################################################################
# spring
####################################################################################################
spring:
  thymeleaf:
    mode: HTML
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxxx
            client-secret: xxxx
